spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/GymCRM1
    username: postgres
    password: damiane1997
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        hbm2ddl.auto: auto
    entities:
      package-to-scan: org.damiane.entity
    repositories:
      bootstrap-mode: deferred


  profiles:
    active: dev